### ISSUE TITLE
IAsyncEnumerable is flagged as requiring runtime support

### ISSUE THREAD

**Issue by lilith** [wallyrion/PolySharp.Playground#7]
Could you add more information about what issue you're seeing? It's a key feature that [should work under PolySharp](https://sergiopedri.medium.com/enabling-and-using-c-9-features-on-older-and-unsupported-runtimes-ce384d8debb) and if there's a bug it would be a big help to have more details.

https://github.com/wallyrion/PolySharp.Playground/blob/master/Polysharp.Playground.CSharp8.RequireRuntime/AsyncStreamExample.cs

**Comment by wallyrion** [comment]
Hello, @lilith!
Thank you for your question and sorry for the long response.

I checked it again and I can see that AsyncEnumerable feature works even without PolySharp. The only change is needed - install Microsoft.Bcl.AsyncInterfaces package.

I changed the documentation in scope of [PR](https://github.com/wallyrion/PolySharp.Playground/pull/8)

But, without Runtime or this additional package , it does not work with PolySharp
